version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: calorie-calculator
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: KnX0212@!
#    volumes:
#      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"